### ISSUE TITLE
Remove --node-modules-dir flag?

### ISSUE THREAD

**Issue by neezer** [bartlomieju/vite-deno-example#4]
What would need to change about Vite/Deno to make this setup work without the `--node-modules-dir` flag?

---

Thanks for putting this together, btw. Super helpful! 👏

**Comment by bartlomieju** [comment]
Vite would need to have a plugin that teaches Parcel how to resolve npm packages from the Deno cache.

**Comment by neezer** [comment]
[Parcel](https://parceljs.org)? What uses Parcel in this setup?

**Comment by bartlomieju** [comment]
Err, sorry... I meant `rollup` of course...

**Comment by neezer** [comment]
Haha, all good. Had me really confused there for a sec. 😅

**Comment by bartlomieju** [comment]
@neezer if your interested in pushing this forward any help would be highly appreciated!
